iosVersion = '14.0'
platform :ios, iosVersion

target 'Tiktok' do
  use_frameworks!
  pod 'TikTokOpenSDK', '~> 5.0.0'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = iosVersion
          config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'NO'
        end
      end
    end
end
